version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: axum_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: axum_crud
    ports:
      - "5432:5432"
    volumes:
      - postgres_:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    volumes:
    - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres_db

volumes:
  postgres_:
    driver: local
  pgadmin_:
    driver: local
